### ISSUE TITLE
fix: update README, LICENSE, and brick descriptions

### ISSUE THREAD

**Issue by felangel** [ana-gallego/andromeda#3]
Hi @ana-gallego 👋
Thanks so much for creating and publishing your bricks!

I noticed all of the bricks are still using the default README, description, and LICENSE. It would be great if you could update the READMEs, descriptions, and LICENSEs of all bricks so that folks will know what the brick is for, how to use it, what it generates, etc.

Thanks!

**Comment by ana-gallego** [comment]
Hi @felangel!
I will be working on it and will update them as soon as I finish.

Thank you!

**Comment by felangel** [comment]
Thanks for the updates! 💯
